version: "3"
services:
  mongodb:
    container_name: db_mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: db_mongo_express
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:${MONGODB_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - 6069:8081
      