version: "3"
services:
  minio:
    container_name: db_minio
    image: minio/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
      - 9069:9069
    command: server /data --console-address ":9069"
