# Example docker-compose file for TimeTagger that uses the published
# Docker image in the default root variant.
# Shows all options settable via the environment.
#
# !! Make sure to apply your own credentials                       !!
# !! You can use e.g. https://timetagger.app/cred to generate them !!
# !! In docker-compose characters '$' should be escaped as '$$'    !!
# !! If you use a .env file, use single quotes instead of escaping !!

version: "3"
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger:latest
    ports:
      - "8708:80"
    volumes:
      - ./data:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
    env_file: .env
