version: "3"
services:
  redis:
    container_name: db_redis
    image: redis/redis-stack
    restart: unless-stopped
    environment:
      REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
      - 7069:8001
