# It is mandatory to provide a self-signed SSL certificate!
# https://actualbudget.org/docs/config/https

services:
  actual-server:
    image: docker.io/actualbudget/actual-server:latest
    restart: unless-stopped
    ports:
      - "8706:5006"
    volumes:
      - ./data:/data
    environment:
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=100
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=175
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=100
